### ISSUE TITLE
pourquoi tu t'embetes avec JSON?

### ISSUE THREAD

**Issue by UnixJunkie** [igarnier/huxiang#1]
Si tu fais du systeme, tu veux des perfs de malade.
Il faut serialiser vers un format binaire, genre Marshal de la stdlib ou bin_prot de janestreet ou le format de serialization des sun rpc (ca doit etre dans ocamlnet) ou encore biniou.
JSON / XML ca a un overhead de malade ces formats et ca n'a surement pas ete invente pour faire du systeme.

**Comment by igarnier** [comment]
Ouais tu as 100% raison. Le seul avantage de JSON c'est que c'est facilement dumpable, pratique pour debugger.
Pour l'instant les perfs sont pas un pb mais dans le futur il faudra clairement que je passe à un autre format de sérialisation. Je vois qu'il ya  des ppx pour bin_prot et pour protobuf, ça sera facile de switcher.
